spring.application.name=smart-city-project
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:file:./data/smartcitydb;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
